# Generated by Django 4.1.5 on 2023-02-03 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plate_num', models.CharField(max_length=256)),
                ('vehicle_type', models.CharField(blank=True, max_length=256, null=True)),
                ('max_capacity', models.IntegerField(default=4)),
                ('special_info', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=256)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=128, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'confirmed'), (2, 'completed')], default=0)),
                ('special_info', models.CharField(blank=True, max_length=256, null=True)),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverToVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='user.vehicle')),
            ],
        ),
    ]
