# Generated by Django 4.1.5 on 2023-02-04 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_alter_order_driver_alter_order_sharer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
